server:
  port: 8099

spring:

  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      url: rediss://default:gQAAAAAAAdfJAAIgcDExOGUyNDA4OGZmMGY0MmMyYmEyZWM1ODRiZTRlM2JkMQ@relaxed-crawdad-120777.upstash.io:6379

  cache:
    type: redis

logging:
  level:
    org:
      springframework:
        data:
          redis: TRACE