name: Terraform plan
on:
  workflow_dispatch:



permissions:
  id-token: write
  contents: read

      
jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    # Add this env block to the job!
    env:
      TF_VAR_aws_region: "ap-south-1"
      TF_VAR_instance_type: "t3.micro"
      TF_VAR_key_name: "backend-key"
      TF_VAR_app_port: "8090"
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gha-terraform-library
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color
